markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /blog/:title/
excerpt_separator: <!--more-->
twitter: Arr0way
twitter_username: Arr0way
gauges_id:
google_analytics_id:
production_url: https://testproject124.github.io
repository: https://github.com/testproject124/testproject124.github.io
url: https://testproject124.github.io
plugins:
  - jekyll-sitemap

collections:
  docs:
    output: true
imagemagick_convert: /usr/local/bin/convert
imagemagick_identify: /usr/local/bin/identify
